### ISSUE TITLE
Ruby 2.7 deprecation warning tracks the method wrongly to new relic line

### ISSUE THREAD

**Issue by bishwahang** [newrelic/newrelic-ruby-agent#349]
I'm not quite sure if this issue belongs here or in Ruby project. 

Ruby tracks the message defined in another library/project to this line on NewRelic gem, https://github.com/newrelic/rpm/blob/main/lib/new_relic/agent/method_tracer.rb#L337, and then throws the deprecation warning.

```ruby
# trigger_profile_confirmed_hooks.rb

class TriggerProfileConfirmedHooks
  Messenger.publish("user.confirmed", {foo: “bar”})
end


# messenger.rb
class Messenger
  def self.publish(message_type, payload = {}, opts = {})
  end
end
```

Warning:

```
app/services/trigger_profile_confirmed_hooks.rb|10 warning| Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/newrelic_rpm-6.11.0.365/lib/new_relic/agent/method_tracer.rb|337 warning| The called method `publish' is defined here
```

Apparently, it happens only for particular method signature. If I change the method name on my project to:
`def something_else(message_type, payload = {}, opts = {})`,
instead of `def publish(message_type, payload = {}, opts = {})`,
the warning goes away.

May be this will go away, when New Relic gem will handle all the 2.7 warnings. Or may be this is related with Ruby wrongly tracing method call.

**Comment by tannalynn** [comment]
Hello @bishwahang 
Thank you for bringing this instance of this warning to our attention. We are working on eliminating these warnings, and will include this instance as well.
We will let you know when we have released this fix.

**Comment by tannalynn** [comment]
Hello @bishwahang !
While looking into these warnings, I learned that this instance of the warning is a little different from the others.
I was able to replicate it by adding methods that match your signatures and adding add_method_tracer for the method. We had already updated the method tracer to use the new kwargs, so I believe the warning is actually coming from the way the method is being called.
When I change
`Messenger.publish("user.confirmed", {foo: “bar”})`
to 
`Messenger.publish("user.confirmed", **{foo: “bar”})`
The warning no longer appears. So adding the double splat to the locations you call the method should remove these warnings for you.

I found this page very helpful in understanding more of the nuances of the keywords arguments changes, personally. https://blog.saeloun.com/2019/10/07/ruby-2-7-keyword-arguments-redesign.html 

Hopefully that helps!

**Comment by bishwahang** [comment]
Hi @tannalynn, thank you for looking into this issue. I was digging a bit into this issue myself too, and I would like to share here.

The following code with similar method signature runs without any warning on `ruby 2.7`, without the double splat **.
```ruby
def say(first_name, attr_1 = {}, attr_2 = {})
  puts "First_name: #{first_name}"
  puts "attr_1: #{attr_1}"
  puts "attr_2: #{attr_2}"
end


attr_1 = { foo: {bar: 2}}
say("John Doe", attr_1)

# outputs
# First_name: John Doe
# attr_1: {:foo=>{:bar=>2}}
# attr_2: {}
```

If i get it right, the double splat should be used if the method expects keyword argument and we are passing hash. It's described in the first example under topic "Typical Case", [here](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0) and it’s also described in article you [shared](https://blog.saeloun.com/2019/10/07/ruby-2-7-keyword-arguments-redesign.html#when-the-method-accept-keywords-and-a-hash-is-passed)

Also, since the warning goes away if I change the method name from `publish` to `anything_else`, it's a bit weird.

I will close this issue. I will write back here again if i find something.

Thank you.

**Comment by Drowze** [comment]
Can we reopen this issue?

NewRelic gem is throwing 2.7 warnings on our codebase. Here is the minimal reproduceable script:

```ruby
require 'newrelic_rpm'

class ComponentRenderer
  def render_component(component_name, options = {})
    puts component_name
    puts options
  end
end

class ComponentRenderer2 < ComponentRenderer
  include ::NewRelic::Agent::MethodTracer

  add_method_tracer :render_component
end

# does not throw warning
ComponentRenderer.new.render_component(:test, { props: { test: 1 } })

# throws warning
ComponentRenderer2.new.render_component(:test, { props: { test: 1 } })
```

**Comment by rachelleahklein** [comment]
Hi @Drowze, we are looking into this. Thanks for the minimal repro, that's very helpful. I'll let you know when there's an update.

**Comment by mwlang** [comment]
This should be solved by this PR: #422

**Comment by gsar** [comment]
also affected by this issue. sadly, moving the `newrelic_rpm` line in the `Gemfile` ahead of `airbrake` doesn't seem to fix it here.

**Comment by angelatan2** [comment]
We are working on this issue within the bug smash milestone.
