### ISSUE TITLE
"Stack too deep" error with scout_apm 4.0.4 and newrelic_rpm 7.0.0

### ISSUE THREAD

**Issue by danielmklein** [newrelic/newrelic-ruby-agent#692]
## Description
We have a Rails application that is using the `scout_apm` gem (version 4.0.4) along with the `newrelic_rpm` gem (version 7.0.0). Every request to this app yields a "Stack too deep" error.

## Expected Behavior
Requests should succeed without errors.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
Stack trace of error looks like this:
```
Puma caught this error: stack level too deep (SystemStackError)
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/depth_first_walker.rb:35:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/depth_first_walker.rb:35:in `block in walk'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:67:in `block (2 levels) in each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each_key'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:66:in `block in each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:65:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:65:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/depth_first_walker.rb:33:in `walk'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/depth_first_walker.rb:36:in `block in walk'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:67:in `block (2 levels) in each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each_key'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:66:in `block in each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:65:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:65:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/depth_first_walker.rb:33:in `walk'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/depth_first_walker.rb:36:in `block in walk'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:67:in `block (2 levels) in each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each_key'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:66:in `block in each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:65:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:65:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/depth_first_walker.rb:33:in `walk'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/depth_first_walker.rb:36:in `block in walk'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:67:in `block (2 levels) in each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each_key'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:66:in `block in each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:65:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:65:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/depth_first_walker.rb:33:in `walk'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/depth_first_walker.rb:36:in `block in walk'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:67:in `block (2 levels) in each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each_key'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:66:in `block in each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:65:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:65:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/depth_first_walker.rb:33:in `walk'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/depth_first_walker.rb:36:in `block in walk'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:67:in `block (2 levels) in each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each_key'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:66:in `block in each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:65:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:65:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/depth_first_walker.rb:33:in `walk'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/depth_first_walker.rb:36:in `block in walk'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:67:in `block (2 levels) in each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each_key'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:66:in `block in each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:65:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:65:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/depth_first_walker.rb:33:in `walk'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/depth_first_walker.rb:36:in `block in walk'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:67:in `block (2 levels) in each'

...snip -- it's just this over and over tens or hundreds of times...

/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each_key'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:66:in `block in each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:65:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:65:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/depth_first_walker.rb:33:in `walk'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/depth_first_walker.rb:36:in `block in walk'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:67:in `block (2 levels) in each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each_key'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:66:in `block in each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:65:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:65:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/depth_first_walker.rb:33:in `walk'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/depth_first_walker.rb:36:in `block in walk'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:67:in `block (2 levels) in each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each_key'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:66:in `block in each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:65:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_children_set.rb:65:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/depth_first_walker.rb:33:in `walk'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/find_layer_by_type.rb:34:in `call'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/find_layer_by_type.rb:24:in `job'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/tracked_request.rb:358:in `job?'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/layer_converters/job_converter.rb:16:in `register_hooks'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/tracked_request.rb:331:in `block in record!'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/tracked_request.rb:329:in `each'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/tracked_request.rb:329:in `inject'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/tracked_request.rb:329:in `record!'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/synchronous_recorder.rb:27:in `record!'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/tracked_request.rb:241:in `stop_request'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/tracked_request.rb:131:in `stop_layer'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/instruments/middleware_summary.rb:60:in `ensure in call'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/scout_apm-4.0.4/lib/scout_apm/instruments/middleware_summary.rb:60:in `call'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.6/lib/rails/engine.rb:527:in `call'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/newrelic_rpm-7.0.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-5.3.2/lib/puma/configuration.rb:249:in `call'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-5.3.2/lib/puma/request.rb:77:in `block in handle_request'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-5.3.2/lib/puma/thread_pool.rb:338:in `with_force_shutdown'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-5.3.2/lib/puma/request.rb:76:in `handle_request'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-5.3.2/lib/puma/server.rb:438:in `process_client'
/Users/daniel/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-5.3.2/lib/puma/thread_pool.rb:145:in `block in spawn_thread'
```

## Steps to Reproduce
1. Set up a rails app with both `scout_apm` 4.0.4 and `newrelic_rpm` 7.0.0` in the Gemfile/Gemfile.lock (with relevant app config)
2. Attempt to execute requests against this app

## Your Environment
Ruby 2.6.6
Dev environment is macOS, staging/production environment is Heroku-20 stack.

## Additional context
Similar issue on the scout_apm GitHub: https://github.com/scoutapp/scout_apm_ruby/issues/404

Downgrading to `newrelic_rpm` 6.15.0 resolves the issue.

**Comment by amovsesy** [comment]
I encountered the same issue and worked with the Scout team. They informed me that this is fixed in 7.1. When will it be released?

**Comment by angelatan2** [comment]
@amovsesy We are working on the release this week.  The plan is to have it released by the end of the week barring anything else that may interrupt the plan.

**Comment by tannalynn** [comment]
7.1.0 was released last week. This version adds ScoutAPM as a known conflict for using Module#prepend on Net::HTTP, so by default, the agent should choose method chaining instrumentation when ScoutAPM is being used. This should solve the issue, but let us know if you run into any other issues.

**Comment by owen2345** [comment]
The problem persists with `newrelic_rpm-7.1.0`
```
/usr/local/bundle/gems/addressable-2.7.0/lib/addressable/uri.rb:895:in `scheme=': stack level too deep (SystemStackError)
[247] ! Unable to load application: SystemStackError: stack level too deep
bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
SystemStackError: stack level too deep
  /usr/local/bundle/gems/addressable-2.7.0/lib/addressable/uri.rb:463:in `initialize_dup'
  /usr/local/bundle/gems/addressable-2.7.0/lib/addressable/uri.rb:463:in `dup'
  /usr/local/bundle/gems/addressable-2.7.0/lib/addressable/uri.rb:463:in `unencode'
```
Removing `newrelic_rpm` from Gemfile it works

**Comment by pznamensky** [comment]
I can confirm that 7.1.0 still not works in all cases with elastic apm 4.2.0.
@tannalynn, could you please reopen the issue?

**Comment by angelatan2** [comment]
Hello @pznamensky, this ticket is related to scout_apm.  For clarity, could you open one for elastic apm and add your error logs, please?

**Comment by tannalynn** [comment]
Hello @owen2345
Is the conflict you are reporting with scout_apm? We added scout apm as a known Module#prepend conflict in 7.1.0, so users that were seeing this specific conflict should no longer see it when the agent uses default instrumentation. 
If you are not using scout apm in the application, it's possible the prepend conflict you are seeing is a conflict with another gem that is using method chaining. 
I see you gave the beginning of the stack trace, but if you look at the full stack trace (not the truncated one) there would be a large section with several lines repeating, those will point to the 2 locations that are using method chaining and Module#prepend. You can set the agent instrumentation to use chain instrumentation in your config, following the [migration guide](https://docs.newrelic.com/docs/agents/ruby-agent/getting-started/migration-7x-guide/#prepend-instrumentation) once you know which of the instrumentation is related to this conflict. If you are unable to figure out which instrumentation needs to be set to chain in the config file, please file a new issue with the full stack trace and I'll help you figure it out.

**Comment by eric-norcross** [comment]
I'm having this same issue using:

- ruby 2.6.6
- rails 6.0.4.4
- puma 4.3.10
- newrelic_rpm 8.3.0
- scout_apm 5.1.1

**Comment by kaylareopelle** [comment]
Hi @eric-norcross! That looks like the newest Scout APM version. They may have changed their code in this version that makes our previous fix no longer compatible. What happens if you update the `instrumentation.net_http` configuration option in your `newrelic.yml` file to `prepend`?

**Comment by eric-norcross** [comment]
@kaylareopelle thanks for the quick response. Unfortunately, the changes you suggested did not resolve the issue. Is there anything else I can try?

**Comment by kaylareopelle** [comment]
Hi @eric-norcross, another option that comes to mind is to update the configuration setting `instrumentation.redis` to `chain`, as this also appeared in the stacktrace. If that doesn't help, could you open a new issue to address this bug?
